version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.svelte
    ports:
      - "5173:5173"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "3333:3333"
    depends_on:
      - database

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: avaa
      POSTGRES_PASSWORD: avaa
      POSTGRES_DB: avaa

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    ports:
      - "6000:6000"
      - "8700:8700"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data/minio
    command: 'minio server /data/minio --console-address ":8700"'

networks:
  local_bridge:
    name: docker_network

volumes:
  psql-data:
  minio:
    driver: local
