name: CI

on:
  push:
    branches:
      - '*'

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure
        working-directory: .venv

  backend-compile:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
        working-directory: backend  
      - name: Compile TypeScript
        run: |
          yarn tsc
        working-directory: backend  

  frontend-compile:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
        working-directory: frontend  
      - name: Compile TypeScript
        run: |
          yarn tsc
        working-directory: frontend  

  frontend-test:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
        working-directory: frontend  
      - name: Run tests
        run: |
          yarn test
        working-directory: frontend  
