name: CI

on:
  push:
    branches:
      - '*'

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config --global user.email "kouahofrancis@gmail.com"
          git config --global user.name "Francis KOUAHO"
          git config --add safe.directory /__w/Plumera/Plumera
      - name: Verify Git status
        run: git status
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure

  backend-compile:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine3.18
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd backend
          yarn install
      - name: Compile TypeScript
        run: |
          cd backend
          yarn tsc

  frontend-compile:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine3.18
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Compile TypeScript
        run: |
          cd frontend
          yarn tsc

#  frontend-test:
#    runs-on: ubuntu-latest
#    container:
#      image: node:21-alpine3.18
#    steps:
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Install dependencies
#        run: |
#          cd frontend
#          yarn install
#      - name: Run tests
#        run: |
#          cd frontend
#          yarn test
